### ISSUE TITLE
关于论文的疑问

### ISSUE THREAD

**Issue by GorgeousMe** [NKU-IIPLab/MSKD#2]
最近非常有幸研读了您的论文，不得不说这篇论文的motivation真是太厉害了！但以下有几点问题我还是没有搞清楚，特向您请教！还望不吝赐教。
1、关于实验：
![image](https://user-images.githubusercontent.com/29190762/173849980-dc9d15f9-c592-4312-ad98-c2bcc7d894f7.png)
首先L*1代表什么意思？是仅仅只有一个隐藏层的GAT么？（L*2/L*3同理）
Optimal Teacher代表什么？（因为这篇论文是多个老师，所以这一项是代表其中性能最高的老师么？）
2、关于论文：
在求graphKL_loss时候我们用的是student的最后一个隐藏层的输出(非logits)与每个teacher的最后一个隐藏层的输出进行求相似度，这里为什么不用logits进行求LS呢？在计算注意力系数时候，我们利用T-S pairs的logits进行点积相似度计算，最后求了一个平均数作为最终系数，我们这么做的原因是什么呢？还有为什么先对Logits进行MLP转换，在求系数？
3、关于代码：
我们在进行优化的时候并不同时对三个teacher同时进行优化的，而是分阶段进行的，先是T1-S，然后再是T2-S，最后是T3-S，这样做的话我们的权重是不是就失去了意义？而且除此之外，我们在warmup_epoch之外进行仅仅是BCELoss半监督训练，graphKL_loss在这段时期已经置为0了。这样训练的合理性是什么？

还望大佬百忙之中给予回复！（来自天津某渣硕一枚），若有幸可以加我Wechat: MyLovelyHuman吗？真想当面讨论一下。

**Comment by wutaiqiang** [comment]
L X 1 代表 L个1层的GNN作为teachers吧，论文的comparison methods里面有写。Optimal Teacher应该指的是最优的teacher，毕竟训了多个teacher，然后选一个最优的。

在求graphKL_loss时候我们用的是student的最后一个隐藏层的输出(非logits)与每个teacher的最后一个隐藏层的输出进行求相似度，这里为什么不用logits进行求LS呢？

**Comment by wutaiqiang** [comment]
![image](https://user-images.githubusercontent.com/28387419/176355096-165e58c7-b691-49ec-ba49-98665e9ae55e.png)
貌似这个PPI的F1是Train set的结果，这篇论文真的是绝绝子
