### ISSUE TITLE
关于训练轮次

### ISSUE THREAD

**Issue by wutaiqiang** [NKU-IIPLab/MSKD#3]
你好，LSP这篇论文中 PPI是训练了500 epoch
但是你的论文里，训练了1500，请问这是不是对比不公平？

**Comment by wutaiqiang** [comment]
https://github.com/NKU-IIPLab/MSKD/blob/b92bfd365083211d99fc0c6ff8c16fcbabafa6b3/main.py#L34

**Comment by wutaiqiang** [comment]
https://github.com/NKU-IIPLab/MSKD/blob/b92bfd365083211d99fc0c6ff8c16fcbabafa6b3/main.py#L250

**Comment by wutaiqiang** [comment]
![image](https://user-images.githubusercontent.com/28387419/177008094-99fb0863-c535-4d77-b564-f0f9aeb27567.png)
论文里说的是500

**Comment by guokedoc** [comment]
> 你好，LSP这篇论文中 PPI是训练了500 epoch 但是你的论文里，训练了1500，请问这是不是对比不公平？

您好，这是因为我们使用的是多老师-学生架构的模型，PPI中使用了三个老师，每个老师用500个epoch做迁移学习。当然1500和500对比是有可能存在问题的，因此我们设计了L*l对比模型，其中L*2就相当于是LSP运行1500个epoch时的性能。可以看到与我们的性能依然有着明显的gap。

**Comment by wutaiqiang** [comment]
感谢回复，请问超参数有啥需要调整的么？我按照默认参数跑，PPI跑完1500只有95的测试集

**Comment by wutaiqiang** [comment]
![image](https://user-images.githubusercontent.com/28387419/177043449-9a725a63-e442-44ad-9fa2-06b7687d4b6e.png)
Teacher的性能是这样的

**Comment by guokedoc** [comment]
> 感谢回复，请问超参数有啥需要调整的么？我按照默认参数跑，PPI跑完1500只有95的测试集

这个性能数值是**相对的**，学生的性能很大程度上依赖于老师的性能，你需要调整一下每个teacher，但是为了和其他论文公平比较，并不是说老师性能越高越合理 (可以参考LSP论文中报告的值)。我们的论文中也报告了optimal teacher的性能。

**Comment by guokedoc** [comment]
你可以参考一下这个



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月3日(星期天) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NKU-IIPLab/MSKD] 关于训练轮次 (Issue #3)





 

 Teacher的性能是这样的

**Comment by wutaiqiang** [comment]
好嘞，感谢感谢，我现在把teacher的训练轮次设为200再试试

**Comment by wutaiqiang** [comment]
https://github.com/NKU-IIPLab/MSKD/blob/b92bfd365083211d99fc0c6ff8c16fcbabafa6b3/topo_semantic.py#L36

![image](https://user-images.githubusercontent.com/28387419/177044411-8cb6c967-733d-4f54-b872-a4e352f2a66e.png)

当然，我发现LSP的论文里也是这么写的，请问你知道为啥这么写么？

**Comment by guokedoc** [comment]
> 好嘞，感谢感谢，我现在把teacher的训练轮次设为200再试试

epoch数最好是不要调的，因为我们的文章沿用了60个。

**Comment by wutaiqiang** [comment]
https://github.com/NKU-IIPLab/MSKD/blob/b92bfd365083211d99fc0c6ff8c16fcbabafa6b3/loss.py#L21
![image](https://user-images.githubusercontent.com/28387419/177044482-5fc1c321-559c-4a17-954b-5c3f26c6e8a9.png)

这块应该是 edgex * （edgex-edgey）吧，为啥是 edgey * （edgex-edgey）

**Comment by wutaiqiang** [comment]
> > 好嘞，感谢感谢，我现在把teacher的训练轮次设为200再试试
> 
> epoch数最好是不要调的，因为我们的文章沿用了60个。

这样，但是我跑出来的teacher效果都很低，只有96
确实可以看 student/teacher的性能，来评估蒸馏的效果。

但是reviewer看的都是绝对指标(无奈)

**Comment by guokedoc** [comment]
> > > 好嘞，感谢感谢，我现在把teacher的训练轮次设为200再试试
> > 
> > 
> > epoch数最好是不要调的，因为我们的文章沿用了60个。
> 
> 这样，但是我跑出来的teacher效果都很低，只有96 确实可以看 student/teacher的性能，来评估蒸馏的效果。
> 
> 但是reviewer看的都是绝对指标(无奈)

之前比较忙，近期会纠正一点代码的小问题，不过大部分内容都还是一样的，你可以先做尝试，有些代码是参考LSP的写法，你可以直接问他们。

**Comment by wutaiqiang** [comment]
> > > > 好嘞，感谢感谢，我现在把teacher的训练轮次设为200再试试
> > > 
> > > 
> > > epoch数最好是不要调的，因为我们的文章沿用了60个。
> > 
> > 
> > 这样，但是我跑出来的teacher效果都很低，只有96 确实可以看 student/teacher的性能，来评估蒸馏的效果。
> > 但是reviewer看的都是绝对指标(无奈)
> 
> 之前比较忙，近期会纠正一点代码的小问题，不过大部分内容都还是一样的，你可以先做尝试，有些代码是参考LSP的写法，你可以直接问他们。

好的，期待新的代码~~
